### PR TITLE
feat: Call a given function after calling the command (PostRun)

### PR DESCRIPTION
**Pull request by GreyXor**
New `postRun` method that allows to automatically call a method after the execution of subcommands. (like preRun but after)

### CODE REVIEW

**Comment by GreyXor** [comment]
Hello @leaanthony :),
Would you like to review and merge this PR ?
Thanks

**Comment by GreyXor** [comment]
@leaanthony ?

**Review by leaanthony — COMMENTED** [review]
Thanks for the ping! This slipped through the net. Just wondering what tests you've done with this

**Comment by GreyXor** [comment]
No problems :) , `postRun()` is effectively used in 2 of my programs since months. And the postRun function is working as expected to me.

**Comment by leaanthony** [comment]
Nice one. Could you please update the docs with the new flag and I'll get this in over the weekend 🙏

**Comment by GreyXor** [comment]
> Nice one. Could you please update the docs with the new flag and I'll get this in over the weekend 🙏

Done, let me know if everything good for you

**Comment by GreyXor** [comment]
@leaanthony hello, gentle ping

**Comment by GreyXor** [comment]
I switched to https://github.com/cristalhq/acmd

**Comment by leaanthony** [comment]
I was just reviewing it too :/

**Comment by GreyXor** [comment]
So feel free to merge it, maybe that can be useful for someone else.

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thanks!

**Comment by GreyXor** [comment]
You're welcome

**Pull request merged**
